FROM python:3.7

WORKDIR /block-producers-directory-telegram-bot
COPY . /block-producers-directory-telegram-bot

ENV PYTHONPATH="$PYTHONPATH:/block-producers-directory-telegram-bot/src"

RUN pip3 install -r /block-producers-directory-telegram-bot/requirements.txt

CMD python3 src/app.py
